#!/bin/sh
# Build and run the mega_progress logic tests.
#
# parse_sense() and classify() are extracted straight out of mega_progress.c,
# and parse_target() out of megaraid_common.h, rather than copied, so the code
# under test is always the code that ships. The tools themselves need a real
# MegaRAID controller, so these three pure functions are the only part that
# can be meaningfully tested off hardware - which is exactly why they are
# tested.
#
# Two passes are run. The plain pass catches logic and offset regressions. The
# AddressSanitizer pass is what gives the bounds checks their teeth: the test
# harness copies each case into an exactly-sized heap allocation, so a parser
# that reads past the declared length trips ASan instead of silently reading
# neighbouring test data. Without it, every bounds check in parse_sense could be
# deleted with the suite still reporting success.
set -e

cd "$(dirname "$0")"

extract() {
    sed -n "/^$1/,/^}/p" "$2"
}

{
    echo "/* Generated by run_tests.sh from mega_progress.c and megaraid_common.h. Do not edit. */"
    sed -n '/^enum drive_state {/,/^};/p' mega_progress.c
    extract "static int parse_sense" mega_progress.c
    extract "static enum drive_state classify" mega_progress.c
    extract "static int64_t parse_expected_block_size" mega_progress.c
    extract "static int check_expected_block_size" mega_progress.c
    extract "static inline int parse_target" megaraid_common.h
    extract "static inline int parse_block_size" megaraid_common.h
    extract "static inline void set_mode_sel_block_length" megaraid_common.h
    extract "static inline int is_unusual_block_size" megaraid_common.h
} > parse_sense.inc

# Guard the extraction. An empty or truncated .inc would otherwise fail the
# compile with a confusing error, or - worse for a range that silently shrinks -
# test less than it appears to.
for want in "static int parse_sense" "static enum drive_state classify" \
            "static int64_t parse_expected_block_size" \
            "static int check_expected_block_size" \
            "static inline int parse_target" "static inline int parse_block_size" \
            "static inline void set_mode_sel_block_length" \
            "static inline int is_unusual_block_size" "enum drive_state {"; do
    if ! grep -q "^$want" parse_sense.inc; then
        echo "FAIL: '$want' missing from parse_sense.inc." >&2
        echo "      run_tests.sh extracts by sed range from mega_progress.c and" >&2
        echo "      assumes each definition starts at column 0 and ends at a" >&2
        echo "      column-0 '}'. Check that assumption still holds." >&2
        exit 1
    fi
done

# Each extracted function must end with exactly one column-0 closing brace; a
# stray '}' at column 0 inside one would truncate it silently.
braces=$(grep -c '^}$' parse_sense.inc)
if [ "$braces" -ne 8 ]; then
    echo "FAIL: expected 8 column-0 closing braces in parse_sense.inc, got $braces" >&2
    echo "      (a '}' at column 0 inside a function truncates the extraction)" >&2
    exit 1
fi

CC=${CC:-cc}

echo "== pass 1: plain =="
$CC -O2 -Wall -Wextra -o test_parse_sense test_parse_sense.c
./test_parse_sense

echo
echo "== pass 2: AddressSanitizer + UndefinedBehaviorSanitizer =="
if $CC -fsanitize=address,undefined -fno-sanitize-recover=all \
       -O1 -g -Wall -Wextra -o test_parse_sense_asan test_parse_sense.c 2>/dev/null; then
    ./test_parse_sense_asan
else
    echo "(sanitizers unavailable with $CC - skipping; the plain pass still ran)"
fi
